workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Skip pipeline for tags
    - if: $CI_COMMIT_BRANCH
      when: always # Run pipeline for all branches

stages:
  - bootstrap
  - html:validate
  - code:release
  - page:deploy

variables:
  CHORE_BOOTSTRAP: '/chore: bootstrap/'

bootstrap:
  image: alpine:latest
  stage: bootstrap
  before_script:
    - apk add --no-cache bash curl jq
  script:
    - chmod +x $CI_PROJECT_DIR/scripts/bootstrap-github.sh
    - $CI_PROJECT_DIR/scripts/bootstrap-github.sh
  # Triggers only from main with the key word bootstrap
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ $CHORE_BOOTSTRAP && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

html:vnu:
  stage: html:validate
  image: cyb3rjak3/html5validator:latest
  script:
    - html5validator --root $CI_PROJECT_DIR

code:release:
  stage: code:release
  image: node:lts
  variables:
    GL_TOKEN: ${RELEASE_BOT_ACCESS_TOKEN}
  before_script:
    - |
      npm i -g \
      semantic-release@24.0.0 \
      @semantic-release/commit-analyzer \
      @semantic-release/release-notes-generator \
      @semantic-release/changelog \
      @semantic-release/git \
      @semantic-release/exec \
      conventional-changelog-conventionalcommits
  script:
    - npx semantic-release --ci
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

page:deploy:
  stage: page:deploy
  script:
    - mkdir public
    - cp -R ./{images,index.html,css} public
    - echo "Pages accessible through ${CI_PAGES_URL}"
  environment:
    name: production
    url: $CI_PAGES_URL
  pages: true  # specifies that this is a Pages job
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
